apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-health-app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./helm-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: health-app
  interval: 1m0s
  targetNamespace: sid
