apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nginx-bitnami
      version: 12.0.3
  interval: 1m0s
  targetNamespace: sid
  values:
    service:
      type: NodePort
