apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ss-kust-2
  namespace: flux-system
spec:
  interval: 300s
  path: ./solar-system
  prune: false
#   patches:
#     - patch: |-
#         apiVersion: apps/v1
#         kind: Deployment
#         metadata:
#           name: solar-system
#         spec:
#           replicas: 4          
#       target:
#         name: solar-system
#         kind: Deployment
  sourceRef:
    kind: GitRepository
    name: solar-system
  targetNamespace: sid
